# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWNLINT
  - SPELL_CSPELL
  - SPELL_MISSPELL
  - YAML_YAMLLINT
DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  # - SPELL # Uncomment to disable checks of spelling mistakes
DISABLE_ERRORS_LINTERS:
  - SPELL_CSPELL
  - SPELL_MISSPELL
  - COPYPASTE_JSCPD
  - YAML_PRETTIER
PRINT_ALL_FILES: false
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (\.github|megalinter-reports)
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: (\.mega-linter\.yml|mega-linter\.yml|\.github|\.devcontainer|megalinter-reports|infra/deployment/*|docs/research/spike-kustomize/*|docs/research/machine-status-investigation/*)
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (\.vscode|\.github|\.devcontainer|megalinter-reports)
SPELL_CSPELL_FILE_EXTENSIONS: [".md", ".ps1", ".psm1", ".cs", ".ipynb"]
LOG_LEVEL: WARNING
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SPELL_VALE_FILE_EXTENSIONS:
  - .md
SPELL_FILTER_REGEX_EXCLUDE: (valestyles|\.github|docs/licenses)
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL3059 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091 --ignore SC3046"
REPOSITORY_TRIVY_ARGUMENTS:
  - "--skip-dirs"
  - ".automation/test"
  - "--skip-dirs"
  - ".venv"
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false
PLUGINS:
  - https://raw.githubusercontent.com/oxsecurity/megalinter/main/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml